name: gut-microbiome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # workflow & plumbing
  - python=3.10
  - snakemake-minimal            # Snakemake without heavy GUIs
  - sra-tools                    # prefetch / fasterq-dump
  - pigz                         # fast gzip (uses little RAM)
  - wget                         # for metadata grabs
  - jq                           # JSON parsing in bash
  - entrez-direct               # esearch / efetch (for list of SRRs)
# optional, installed later
  # - fastp
  # - metaphlan
  # - humann
  # - r-base
